[theme]
primaryColor = "#D4AF37"  # Couleur or pour les boutons et les accents
backgroundColor = "#0E1117"  # Fond sombre
secondaryBackgroundColor = "#1C1E26"  # Fond du sidebar
textColor = "#FFFFFF"  # Texte en blanc
font = "sans serif"
